### ISSUE TITLE
[Feature Request] Pull full sized images that retain Prompt Meta

### ISSUE THREAD

**Issue by shaneholloman** [tehrobber/civitai-one-click-dl#4] opened 2023-02-13 11:20 UTC
Pulling the full sized images is very helpful. It's a simple way to retain a record of how the author is generating intended results.
What if CivitAI dies one day?

![image](https://user-images.githubusercontent.com/1563909/218443033-4190e44f-10b6-43e8-97f3-eb7b81bf4866.png)
 
vs

![image](https://user-images.githubusercontent.com/1563909/218443372-cf4337bb-b0cc-4fab-8513-8b149804a604.png)

I hope this is helpful and not irritating ??

**Comment by tehrobber** [comment] 2023-02-13 22:04
This should be fixed with version 1.1, can you try reinstalling the script?

I'll give a look into why updating isn't working.

**Comment by tehrobber** [comment] 2023-02-13 22:04
This should be fixed with version 1.1, can you try reinstalling the script?

I'll give a look into why updating isn't working.

**Comment by tehrobber** [comment] 2023-02-14 05:49
![image](https://user-images.githubusercontent.com/83055339/218650644-b0c24912-219e-4e02-9f9a-084402799e74.png)
I fixed the update.

Latest is 1.3.1 and I confirmed metadata is there.
Closing since this is resolved.

**Closed as completed by tehrobber** 2023-02-14 05:49 UTC
